
name: Test Frontend => workflow name

# Controls when the workflow will run
on: 
  pull_request:
    branches: [ "main" ]
    paths: 
      - "frontend/**" #when code changes of frontend folder

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  # This workflow contains a single job called "test_frontend"
 
   test_frontend: 
     name: Test frontend folder 
     runs-on: ubuntu-latest # The type of runner that the job will run on


     # Steps represent a sequence of tasks that will be executed as part of the job
     steps: 
       - name: checking out repository code
         uses: actions/checkout@v3  # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

       - name: run frontend test file
         run: |
          cd frontend
          node test.js

 
    
